### ISSUE TITLE
Ciągłe zwiechy

### ISSUE THREAD

**Issue by andrewmyles2** [mandrzejczyk/save_soup#2]
Ten program wiesza się częściej niż samobójczy nastolatek na tumblerze. 

Wywala mnie do linii komend, mówiąc, że "Error occured when downloading last content". Byłoby fajnie, gdyby:

1) nie robił tego i umiał się restartować
2) zapisywał w last_page numer ostatniego pliku
3) potrafił czytać z last_page, żebyśmy nie musieli tego wpisywać ręcznie i móc odpalić go na noc, an nie zerkać co pięć minut, czy bąbelek nie zrobił sobie ku-ku.

**Comment by andrewmyles2** [comment]
![seriokurwa](https://user-images.githubusercontent.com/66495274/87480673-187f1b80-c62e-11ea-9665-5414102c1a48.jpg)

Chwila, to coś próbuje załadować zupę tylko pięć razy? Przecież to zupa!

**Comment by andrewmyles2** [comment]
Okej, coś się kompletnie spieprzyło. Program sciąga w kółko te same 4 rysunki (z tej strony: https://andrewmyles.soup.io/since/660320261), w ogólne nie próbując przejść dalej, pomimo tego, że dobrze ustawiam te cholerne liczby i że na stronie, na której się zacina jest więcej obrazków.

**Comment by andrewmyles2** [comment]
Ręczne przejście do nowej strony na /since naprawiło, ale wciąż, zajęło mi to cztery próby i nie powinniśmy tego robić ręcznie...

**Comment by mandrzejczyk** [comment]
Obsługę strony "Don't panic" dodałem dziś. W weekend serwery zupy jeszcze żyły i wszystko pięknie śmigało.
Co do liczby powtórzeń to specjalnie dałem tylko 5, bo nie chciałem bez sensu obciążać zupie serwera.

**Comment by mandrzejczyk** [comment]
dodałem też więcej powtórzeń
